"""create prices table

Revision ID: a1e8aaa9fa15
Revises: 
Create Date: 2026-03-16 10:59:53.565777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e8aaa9fa15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='Instrument name (BTC_USD, ETH_USD)'),
    sa.Column('price', sa.Float(), nullable=False, comment='price in USD'),
    sa.Column('timestamp', sa.Integer(), nullable=False, comment='UNIX timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
